# Site settings
title: CALL FOR MENTAL HEALTH '20
email: mail@call-for-mental-health.eu
url: https://call-for-mental-health.eu
description: "call for mental health 2020"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: CALL FOR MENTAL HELATH '20

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitch
    url: https://twitch.tv/call-for-mental-health

# Build settings
markdown: kramdown
permalink: pretty
